name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m venv ./.python3
          source .python3/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -U -r requirements.txt

      - name: Install compiler
        run: |
            scripts/setup_compiler.sh

      - name: Setup Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

            
      - name: Setup build environment
        run: |
          sudo apt-get install -y binutils-mips-linux-gnu
          mkdir -p iso
          wget --no-check-certificate "${{ secrets.FILE_URL }}" -O iso/SCPS_150.97
          wget --no-check-certificate "${{ secrets.KERNEL_URL }}" -O iso/KERNEL.XFF

      - name: Build main ELF
        run: |
          make loader

      - name: Build KERNEL.XFF
        run: |
          make kernel

      - name: Post to frogress endpoint
        run: |
          python3 scripts/upload_progress.py --frogress_api_key ${{ secrets.FROGRESS_API_KEY }}
